export const GetCctvData = async (selectedArea, selectedGubun) => {
    const url = `http://localhost:4000/api/cctv`;
    const response = await fetch(url);
    const data = await response.json();

    let locations = [];
    
    // 도시별 구군 매핑
    const areaMapping = {
        "서울특별시": {
            "강남구": "GangNam",
            "강동구": "GangDong",
            "강북구": "GangBuk",
            "강서구": "GangSeo",
            "관악구": "GwanAk",
            "광진구": "GwangJin",
            "구로구": "GuRo",
            "금천구": "GeumCheon",
            "노원구": "NoWon",
            "동대문구": "DongDaeMun",
            "동작구": "DongJak",
            "마포구": "MaPo",
            "서대문구": "SeoDaeMun",
            "서초구": "SeoCho",
            "성동구": "SeongDong",
            "성북구": "SeongBuk",
            "송파구": "SongPa",
            "양천구": "YangCheon",
            "영등포구": "YeongDeungPo",
            "용산구": "YongSan",
            "은평구": "EunPyeong",
            "종로구": "JongNo",
            "중구": "Jung",
            "중랑구": "JungNang"
        },
        "부산광역시": {
            "강서구": "GangSeo",
            "금정구": "GeumJeong",
            "남구": "Nam",
            "동구": "Dong",
            "동래구": "DongNae",
            "부산진구": "BusanJin",
            "북구": "Buk",
            "사상구": "SaSang",
            "사하구": "SaHa",
            "서구": "Seo",
            "수영구": "SuYeong",
            "연제구": "YeonJe",
            "영도구": "YeongDo",
            "중구": "Jung",
            "해운대구": "HaeUnDae",
            "기장군": "GiJang",
        },
        "대구광역시": {
            "남구": "Nam",
            "달서구": "Dalseo",
            "동구": "Dong",
            "북구": "Buk",
            "서구": "Seo",
            "수성구": "Suseong",
            "중구": "Jung",
            "달성군": "Dalseong",
            "군위군": "Gunwi",
        },
        "인천광역시": {
            "계양구": "Gyeyang",
            "미추홀구": "Michuhol",
            "남동구": "Namdong",
            "동구": "Dong",
            "부평구": "Bupyeong",
            "서구": "Seo",
            "연수구": "Yeonsu",
            "중구": "Jung",
            "강화군": "Ganghwa",
            "옹진군": "Ongjin",
        },
        "광주광역시": {
            "광산구": "Gwangsan",
            "남구": "Nam",
            "동구": "Dong",
            "북구": "Buk",
            "서구": "Seo",
        },
        "대전광역시": {
            "대덕구": "Daedeok",
            "동구": "Dong",
            "서구": "Seo",
            "유성구": "Yuseong",
            "중구": "Jung",
        },
        "울산광역시": {
            "남구": "Nam",
            "동구": "Dong",
            "북구": "Buk",
            "중구": "Jung",
            "울주군": "Ulju",
        },
        "세종특별자치시": {
            "세종특별자치시": "Sejong",
        },
        "경기도": {
            "수원시": "Suwon",
            "고양시": "Goyang",
            "과천시": "Gwacheon",
            "광명시": "Gwangmyeong",
            "광주시": "Gwangju",
            "구리시": "Guri",
            "군포시": "Gunpo",
            "김포시": "Gimpo",
            "남양주시": "Namyangju",
            "동두천시": "Dongducheon",
            "부천시": "Bucheon",
            "성남시": "Seongnam",
            "시흥시": "Siheung",
            "안산시": "Ansan",
            "안성시": "Anseong",
            "안양시": "Anyang",
            "양주시": "Yangju",
            "여주시": "Yeoju",
            "오산시": "Osan",
            "용인시": "Yongin",
            "의왕시": "Uiwang",
            "의정부시": "Uijeongbu",
            "이천시": "Icheon",
            "파주시": "Paju",
            "평택시": "Pyeongtaek",
            "포천시": "Pocheon",
            "하남시": "Hanam",
            "화성시": "Hwaseong",
            "가평군": "Gapyeong",
            "양평군": "Yangpyeong",
            "연천군": "Yeoncheon",
        },
        "강원특별자치도": {
            "춘천시": "Chuncheon",
            "강릉시": "Gangneung",
            "동해시": "Donghae",
            "삼척시": "Samcheok",
            "속초시": "Sokcho",
            "원주시": "Wonju",
            "태백시": "Taebaek",
            "고성군": "Goseong",
            "양구군": "Yanggu",
            "양양군": "Yangyang",
            "영월군": "Yeongwol",
            "인제군": "Inje",
            "정선군": "Jeongseon",
            "철원군": "Cheorwon",
            "평창군": "Pyeongchang",
            "홍천군": "Hongcheon",
            "화천군": "Hwacheon",
            "횡성군": "Hoengseong",
        },
        "충청북도": {
            "청주시": "Cheongju",
            "제천시": "Jecheon",
            "충주시": "Chungju",
            "괴산군": "Goesan",
            "단양군": "Danyang",
            "보은군": "Boeun",
            "영동군": "Yeongdong",
            "옥천군": "Okcheon",
            "음성군": "Eumsung",
            "증평군": "Jeungpyeong",
            "진천군": "Jincheon",
        },
        "충청남도": {
            "천안시": "Cheonan",
            "공주시": "Gongju",
            "아산시": "Asan",
            "보령시": "Boryeong",
            "서산시": "Seosan",
            "논산시": "Nonsan",
            "계룡시": "Gyeryong",
            "당진시": "Dangjin",
            "부여군": "Buyeo",
            "서천군": "Seocheon",
            "청양군": "Cheongyang",
            "홍성군": "Hongseong",
            "예산군": "Yesan",
            "태안군": "Taean",
            "금산군": "Geumsan",
        },
        "전북특별자치도": {
            "전주시": "Jeonju",
            "군산시": "Gunsan",
            "익산시": "Iksan",
            "정읍시": "Jeongeup",
            "남원시": "Namwon",
            "김제시": "Gimje",
            "완주군": "Wanju",
            "진안군": "Jinan",
            "무주군": "Muju",
            "장수군": "Jangsu",
            "임실군": "Imsil",
            "순창군": "Sunchang",
            "고창군": "Gochang",
            "부안군": "Buan",
        },
        "전라남도": {
            "목포시": "Mokpo",
            "여수시": "Yeosu",
            "순천시": "Suncheon",
            "나주시": "Naju",
            "광양시": "Gwangyang",
            "담양군": "Damyang",
            "곡성군": "Gokseong",
            "구례군": "Gurye",
            "고흥군": "Goheung",
            "보성군": "Boseong",
            "화순군": "Hwasun",
            "장흥군": "Jangheung",
            "강진군": "Gangjin",
            "해남군": "Haenam",
            "영암군": "Yeongam",
            "무안군": "Muan",
            "함평군": "Hampyeong",
            "영광군": "Yeonggwang",
            "장성군": "Jangseong",
            "완도군": "Wando",
            "진도군": "Jindo",
            "신안군": "Sinan",
        },
        "경상북도": {
            "포항시": "Pohang",
            "안동시": "Andong",
            "구미시": "Gumi",
            "경주시": "Gyeongju",
            "경산시": "Gyeongsan",
            "영주시": "Yeongju",
            "영천시": "Yeongcheon",
            "상주시": "Sangju",
            "문경시": "Mungyeong",
            "김천시": "Gimcheon",
            "칠곡군": "Chilgok",
            "의성군": "Uiseong",
            "성주군": "Seongju",
            "고령군": "Goryeong",
            "예천군": "Yecheon",
            "봉화군": "Bonghwa",
            "울진군": "Uljin",
            "영덕군": "Yeongdeok",
            "청송군": "Cheongsong",
            "영양군": "Yeongyang",
            "청도군": "Cheongdo",
            "울릉군": "Ulleung",
        },
        "경상남도": {
            "창원시": "Changwon",
            "진주시": "Jinju",
            "사천시": "Sacheon",
            "김해시": "Gimhae",
            "밀양시": "Miryang",
            "양산시": "Yangsan",
            "통영시": "Tongyeong",
            "거제시": "Geoje",
            "함안군": "Haman",
            "창녕군": "Changnyeong",
            "의령군": "Uiryeong",
            "고성군": "Goseong",
            "남해군": "Namhae",
            "산청군": "Sancheong",
            "합천군": "Hapcheon",
            "거창군": "Geochang",
            "함양군": "Hamyang",
            "하동군": "Hadong",
        },
        "제주특별자치도": {
            "제주시": "Jeju",
            "서귀포시": "Seogwipo",
        }
    };

    // `selectedArea`를 `sido`와 `gugun`으로 분리
    const [sido, gugun] = selectedArea.split(" ");

    // 시도와 구군 정보를 사용하여 데이터 가져오기
    if (areaMapping[sido] && areaMapping[sido][gugun]) {
        // 시도에 따라 data에서 city 값을 설정
        const cityMapping = {
            "서울특별시": "Seoul",
            "부산광역시": "Busan",
            "대구광역시": "Daegu",
            "인천광역시": "Incheon",
            "광주광역시": "Gwangju",
            "대전광역시": "Daejeon",
            "울산광역시": "Ulsan",
            "세종특별자치시": "Sejong",
            "경기도": "Gyeonggi",
            "강원특별자치도": "Gangwon",
            "충청북도": "Chungbuk",
            "충청남도": "Chungnam",
            "전북특별자치도": "Jeonbuk",
            "전라남도": "Jeonnam",
            "경상북도": "Gyeongbuk",
            "경상남도": "Gyeongnam",
            "제주특별자치도": "Jeju"
        };

        const city = cityMapping[sido];
        const district = areaMapping[sido][gugun];

        if (city && data[city] && data[city][0][district]) {
            locations = data[city][0][district]
                .filter(spot => selectedGubun.includes(spot.Gubun)) // gubun으로 필터링
                .map(spot => [
                    spot.lo,
                    spot.la,
                    spot.Address1,
                    spot.Address2,
                    spot.Gubun,
                    spot.Camera,
                    spot.Bogwan,
                    spot.MakeDate,
                    spot.Number
                ]);
        }
    }

    return locations;
};